### ISSUE TITLE
(wrongly added)

### ISSUE THREAD

**Issue by gvassas** [HatfieldConsultants/AquariusDataImporter#5]

**Comment by gvassas** [comment]
This issue was moved to HatfieldConsultants/AquariusDataImporter#3

**Comment by gvassas** [comment]
This issue was moved to HatfieldConsultants/AquariusDataImporter#4

**Comment by mikechiang** [comment]
Hi,

I shouldn't be receiving these notifications, please remove me from this 
group.

Cheers,
Mike

**Comment by daniellu** [comment]
Hey Mike,

You are in the watching list of the project. You need to go to github to
unwatch the project. We can not change your account's setup.

Regards,
Daniel

**Comment by mikechiang** [comment]
I see, thanks Daniel!
